config/routes.rb
Rails.application.routes.draw do

 root 'main#index'

 #get '1810', to: 'main#index', as: :main_index

 post 'upload_img', to: 'uploads#img', as: :upload_img

 post 'load_main_frame', to: 'main#load_main_frame', as: :load_main_frame

 post 'registrar_participante', to: 'main#registrar_participante', as: :registrar_participante

 get 'felicidades', to: 'main#felicidades', as: :main_felicidades

 get 'galeria', to: 'main#galeria', as: :main_galeria

 namespace :dynamic_select do
  get ':region_id/provincias', to: 'provincias#index', as: 'provincias'
 end

end

app/models/participante.rb
class Participante < ActiveRecord::Base
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :uploads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/cipher.rb
class Cipher

  extend ActiveSupport::Concern

  def initialize(shuffled)
    normal = ('a'..'z').to_a + ('A'..'Z').to_a + ('0'..'9').to_a + [' ']
    @map = normal.zip(shuffled).inject(:encrypt => {} , :decrypt => {}) do |hash,(a,b)|
      hash[:encrypt][a] = b
      hash[:decrypt][b] = a
      hash
    end
  end

  def encrypt(str)
    str.split(//).map { |char| @map[:encrypt][char] }.join
  end

  def decrypt(str)
    str.split(//).map { |char| @map[:decrypt][char] }.join
  end

end

app/controllers/dynamic_select/provincias_controller.rb
module DynamicSelect
  class ProvinciasController < ApplicationController

    respond_to :json

    def index
      @provincias = Provincia.where(:region_id => params[:region_id])
      respond_with(@provincias)
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_action :check_participante_registrado, only: :registrar_participante
	included Cipher

	def index
	end

	def load_main_frame
		render partial: 'main'
	end

	def registrar_participante
		@participante = Participante.find_by(email: participante_params[:email])
		if @participante.nil?
			@participante = Participante.new(participante_params)
			respond_to do |format|
				if @participante.save
					format.html { redirect_to main_felicidades_path(sc: @participante.id) and return }
				else
					format.html {redirect_to root_path and return }
				end
			end
		else
			respond_to do |format|
				if @participante.update(participante_params)
					format.html { redirect_to main_felicidades_path(sc: @participante.id) and return }
				else
					format.html {redirect_to root_path and return }
				end
			end
		end
	end

	def felicidades
		participante = Participante.find_by(id:  ActionController::Parameters.new(sc: params[:sc]).permit(:sc)[:sc])
		user = User.find_by_email(participante.email) if participante.present?
		if user.present? && user.email.present? && user.photo_count.present?
			cipher = Cipher.new ["K", "D", "w", "X", "H", "3", "e", "1", "S", "B", "g", "a", "y", "v", "I", "6", "u", "W", "C", "0", "9", "b", "z", "T", "A", "q", "U", "4", "O", "o", "E", "N", "r", "n", "m", "d", "k", "x", "P", "t", "R", "s", "J", "L", "f", "h", "Z", "j", "Y", "5", "7", "l", "p", "c", "2", "8", "M", "V", "G", "i", "Q", "F"]
			@img = cipher.encrypt(user.email + '_' + (user.photo_count - 1 ).to_s)
			@id = user.id
		else
			redirect_to root_url and return
		end
	end


	def galeria
		cipher = Cipher.new ["K", "D", "w", "X", "H", "3", "e", "1", "S", "B", "g", "a", "y", "v", "I", "6", "u", "W", "C", "0", "9", "b", "z", "T", "A", "q", "U", "4", "O", "o", "E", "N", "r", "n", "m", "d", "k", "x", "P", "t", "R", "s", "J", "L", "f", "h", "Z", "j", "Y", "5", "7", "l", "p", "c", "2", "8", "M", "V", "G", "i", "Q", "F"]
		last = User.last
		if last.id == 1
			ids = [1]
		elsif last.id < 50
			ids = (1..last.id).to_a.sort{ rand() - 0.5 }[0..last.id]
		else
			ids = (1..last.id).to_a.sort{ rand() - 0.5 }[0..50]
		end
		@img = Array.new
		ids.each do |id|
			user = User.find_by(id: id)
			if user.present? && user.email.present? && user.photo_count > 0
				hash = Hash.new
				hash[:img] = cipher.encrypt(user.email + '_' + (user.photo_count - 1 ).to_s) if user.present?
				hash[:id] = id if user.present?
				@img << hash if user.present?
			end
		end
	end

	def old

	end

	private

		def participante_params
			params.require(:participante).permit(:nombre, :fecha_nacimiento, :provincia_id, :email)
		end

		def check_participante_registrado
			participante = Participante.find_by(email: participante_params[:email])
			if participante.present?
				redirect_to main_felicidades_path(sc: participante.id) and return
			end
		end
	
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  respond_to :json
	require 'base64'
	included Cipher

  def img
		email = ActionController::Parameters.new(email: params[:email]).permit(:email)[:email]
		data =  ActionController::Parameters.new(img: params[:img]).permit(:img)[:img]
		unless email.nil? || data.nil?
			user = User.find_by(email: email) || User.create(email: email, photo_count: 1)
			cipher = Cipher.new ["K", "D", "w", "X", "H", "3", "e", "1", "S", "B", "g", "a", "y", "v", "I", "6", "u", "W", "C", "0", "9", "b", "z", "T", "A", "q", "U", "4", "O", "o", "E", "N", "r", "n", "m", "d", "k", "x", "P", "t", "R", "s", "J", "L", "f", "h", "Z", "j", "Y", "5", "7", "l", "p", "c", "2", "8", "M", "V", "G", "i", "Q", "F"]
			file_name = cipher.encrypt(user.email + '_' + user.photo_count.to_s)
			image_data = Base64.decode64(data['data:image/png;base64,'.length .. -1])
			directory_name = "#{Rails.root}/public/#{user.id}"
			Dir.mkdir(directory_name) unless File.exists?(directory_name)

			File.open("#{Rails.root}/public/#{user.id}/#{file_name}.png", 'wb') do |f|
				if f.write image_data
					current_photos = user.photo_count + 1
					user.update_column(:photo_count, current_photos)
					render json: "http://nosunelaparrilla.cl/#{user.id}/#{file_name}.png".to_json
					return
				else
					render json: 'false'.to_json
					return
				end
			end
		else
			render json: 'false'.to_json
			return
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/main/_main.html.haml
= image_tag 'pantalla_1/logo_bg.png', class: 'logo_bg img-responsive'

.vcenter
  .row
    .col-xs-12
      .container
        .row
          .col-xs-3.text-right.col_izquierda

            .row.row_nombre_usuario
              .col-xs-12
                %p.nombre_usuario#nombre_usuario_p
                %p.apellido_usuario#apellido_usuario_p
            .row.aux_relative
              .col-xs-12
            .row
              .col-xs-12
                = image_tag 'pantalla_2/adorno_izquierdo.png', class: 'adorno_izquierdo'
            .row.row_texto
              .col-xs-12
                = image_tag 'pantalla_2/texto.png', class: 'img-responsive', id: 'texto_1'
                = image_tag 'pantalla_3/texto_2.png', class: 'img-responsive', id: 'texto_2', style: 'display:none;'
          .col-xs-6.text-center.col_medio

            .row
              .col-xs-12
                .portrait#canvas_video_div
                  #pintura_div{style: 'display:none;'}
                  .frame01#frame_div
                  .pic_frame
                    .ci-main-canvas
                      #canvas_container.ci-canvas-wrapper
                        = image_tag 'pantalla_2/aviso formato.png', class: 'img-responsive aviso', id: 'aviso_formato', style: 'display:none;'
                        = image_tag 'pantalla_2/aviso tamano.png', class: 'img-responsive aviso', id: 'aviso_tamano', style: 'display:none'
                        %video.video#video{:autoplay => "", :height => "360", :width => "360"}
                        %canvas.canvas.ui-widget-content#canvas{:height => "360", :style => "", :width => "360"}
                      #img_canvas_output.ci-canvas-wrapper{style:'display:none'}
                    #img_container{style: 'position:absolute;'}
                %input.zoom-range#zoom-range{:type => "range", style: 'display:none;'}
                .formulario#formulario_div{style: 'display:none'}
                  .row
                    .col-xs-12
                      %h4.title_formulario
                        PARA FINALIZAR INGRESA ESTOS DATOS
                  .row
                    .col-xs-11
                      = form_for :participante, url: registrar_participante_path,  html: {id: 'form_participante', class: 'form-horizontal'} do |f|
                        .form-group
                          = f.label :nombre, class: 'col-xs-4 control-label' do
                            Nombre:
                          .col-xs-8
                            = f.text_field :nombre, readonly: true, class: 'form-control'
                        .form-group
                          = f.label :fecha_nacimiento, class: 'col-xs-4 control-label' do
                            Fecha de Nacimiento:
                          .col-xs-8
                            /= f.date_select :fecha_nacimiento, start_year: 1930, end_year: Date.today.year, order: [:day, :month, :year],  prompt: { day: 'Día', month: 'Mes', year: 'Año' }, use_month_names: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre'], class: 'form-control'
                            = f.text_field :fecha_nacimiento, class: 'form-control'
                        .form-group
                          = f.label :region, class: 'col-xs-4 control-label' do
                            Región:
                          .col-xs-8
                            = collection_select :region, :region, Region.all, :region_id, :region_nombre, { include_blank: 'Selec. una Región'},
                              data: { dynamic_selectable_url: dynamic_select_provincias_path(':region_id'), dynamic_selectable_target: '#participante_provincia_id' }, class: 'form-control'
                        .form-group
                          = f.label :provincia, class: 'col-xs-4 control-label' do
                            Ciudad:
                          .col-xs-8
                            = f.select :provincia_id, options_from_collection_for_select(Provincia.all, :provincia_id, :provincia_nombre), {:include_blank => 'Selec. una Ciudad'}, class: 'form-control'
                        .form-group
                          = f.label :email, class: 'col-xs-4 control-label' do
                            Email:
                          .col-xs-8
                            = f.text_field :email, readonly: true,  class: 'form-control'
                        .form-group
                          .col-xs-8.col-xs-offset-2.text-center.terminos_condiciones{style: 'font-size:10px; margin-top: -5px; margin-bottom: -10px;'}
                            %p
                              Al presionar enviar estas aceptando nuestros
                              = link_to '/privacy.pdf' do
                                términos y condiciones
                              de uso.
                        .form-group
                          .col-xs-12
                            %button#boton_enviar{type: "submit" , style: 'display:block; margin-left: auto; margin-right: auto;'}
                              = image_tag 'pantalla_4/enviar-on.png', class: 'boton_enviar_img'
                = image_tag 'pantalla_1/adorno_btn_fb.png' , class: 'img-responsive', id: 'm_adorno_form', style: 'display:none;'
              .col-xs-12#html2canvas_col{style: 'display:none'}
                .portrait
                  #html2canvas_output
          = image_tag 'movil/pantalla_2/texto_artemarco.png', class: 'm_texto_artemarco', style: 'display:none', id:'m_texto_artemarco'
          = image_tag 'movil/pantalla_3/texto_foto.png', class: 'm_texto_foto', style: 'display:none', id: 'm_texto_foto'
          .col-xs-3.text-center.col_derecha
            .row.row_subir_imagen#form_div{style: 'display:none'}
              .col-xs-12
                = form_for :upload, url: upload_img_path,  html: { multipart: true }, remote: true do | f |
                  .file_input_div
                    %label.label_file_input{for: 'file-input'}
                      = image_tag 'pantalla_2/subir_imagen.png', class: 'file-input-img subir_imagen'
                      = image_tag 'movil/pantalla_3/m_subir_imagen.png', class: 'file-input-img subir_imagen_m', style: 'display:none'
                    = f.file_field :file_input, id: 'file-input', class: 'file_input'
            .row_cambiar_arte#cambiar_arte_div
              %button#cambiar_marco{"data-target" => ".bs-cuadros-modal-lg", "data-toggle" => "modal", :type => "button"}
                = image_tag 'pantalla_3/cambia_marco.png', class: 'cambiar_marco_img'
                = image_tag 'movil/pantalla_2/m_cambia_marco.png', class: 'cambiar_marco_m', style: 'display:none'
            .row.aux_relative
              .col-xs-12
            .row.row_adorno_derecho
              .col-xs-12
                = image_tag 'pantalla_2/adorno_derecho.png', class: 'adorno_derecho'
            .row_continuar#row_continuar{style:'display:none'}
              %button#boton_continuar{"data-toggle" => "tooltip", "title" => "Continuar"}
                = image_tag 'pantalla_2/continuar.png', class: 'boton_continuar_r'
            .row_compartir#row_compartir{style: 'display:none'}
              %button#boton_compartir{"data-toggle" => "tooltip", "title" => "Compartir en Facebook"}
                = image_tag 'pantalla_3/compartir-on.png', class: 'boton_compartir_r'
              %button#boton_compartir_off{style: 'display:none',disabled: 'disabled',"data-toggle" => "tooltip", "title" => "Debes seleccionar un arte para poder compartir"}
                = image_tag 'pantalla_3/compartir-off.png', class: 'boton_compartir_r'
              %i.fa.fa-circle-o-notch.fa-2x.fa-spin#loading_facebook_share{style: 'display:none'}
            .row.row_encender_camara
              .col-xs-12
                %button#cambiar_arte{"data-target" => ".bs-pinturas-modal-lg", "data-toggle" => "modal", :type => "button"}
                  = image_tag 'pantalla_2/cambia_el_personaje.png', class: 'cambiar_personaje_img'
                  = image_tag 'movil/pantalla_2/m_cambia_arte.png', class: 'cambiar_arte_m', style: 'display:none'
                %button#camara_on{style: 'display:none'}
                  = image_tag 'pantalla_2/encender_camara.png', class: 'img-responsive'
                %button#snap{style: 'display:none'}
                  = image_tag 'pantalla_3/tomar_foto.png', class: 'img-responsive'
                %button#retake.sexyButton{:style => "display:none;"}
                  = image_tag 'pantalla_3/retomar_foto.png', class: 'img-responsive'
.row
  .col-xs-12
    = image_tag 'pantalla_2/navigation_1.png', class: 'navigation', id: 'navigation_1'
    = image_tag 'pantalla_2/navigation_2.png', class: 'navigation', id: 'navigation_2', style: 'display:none'
    = image_tag 'pantalla_2/navigation_3.png', class: 'navigation', id: 'navigation_3', style: 'display:none'


= render partial: 'partial_modal_pinturas'

= render partial: 'partial_modal_cuadros'

app/views/main/_main_old.html.haml
/ ROW DE BOTONES UP
.row.row_up
  .col-xs-3.col-xs-offset-3
    %a#camara_on.btn.btn-default{:href => "#"} Encender Cámara
  .col-xs-3
    = form_for :upload, url: upload_img_path,  html: { multipart: true }, remote: true do | f |
      = f.file_field :file_input, id: 'file-input'
      %input#x{:name => "x", :style => "display:none;", :type => "text", :value => "0"}/
      %input#y{:name => "y", :style => "display:none;", :type => "text", :value => "0"}/
      %input#w{:name => "w", :style => "display:none;", :type => "text", :value => "0"}/
      %input#h{:name => "h", :style => "display:none;", :type => "text", :value => "0"}/
/%input#upload_button.submit{:style => "display:none;", :type => "submit", :value => "Upload"}/

/ ROW DE CANVAS Y VIDEO
.row
  / COLUMNA DE CANVAS Y VIDEO
  .col-xs-8
    .portrait#canvas_video_div
      #pintura_div{style: 'display:none;'}
      .frame01#frame_div
      .pic_frame
        .ci-main-canvas
          #canvas_container.ci-canvas-wrapper
            %video#video{:autoplay => "", :height => "358", :width => "355"}
            %canvas#canvas.ui-widget-content{:height => "358", :style => "", :width => "355"}
          #img_canvas_output.ci-canvas-wrapper{style:'display:none'}
        #img_container
        #message
  .col-xs-8#html2canvas_col{style: 'display:none'}
    .portrait
      #html2canvas_output
  / COLUMNA DE CAMBIAR ARTE Y MARCO
  .col-xs-4
    .row
      .col-xs-12
        %button#cambiar_arte
          Cambia el Arte
    .row
      .col-xs-12
        %button#upload_photo_button{style: 'display:none;'}
          Compartir
    .row
      .col-xs-12

          Cambia el Marco

/ ROW DE BOTONES DOWN
.row
  .col-xs-12
    #buttons
      %button#snap{style: 'display:none'} Tomar Foto
      %button#retake.sexyButton{:style => "display:none;"} Retomar

app/views/main/_modal_parrilleros.html.haml
/ MODAL Parrilleros
.modal.fade.bs-parrilleros-modal-lg.autoModal#modal_parrilleros{"aria-labelledby" => "parrillerosModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .row{style: 'position: absolute;    top: 50%;    left: 50%;'}
          .col-xs-12.text-center
            %i.fa.fa-circle-o-notch.fa-5x.fa-spin
        .row
          .col-xs-12
            #productos_parrilleros
              .fluid_container
                #camera_wrap.camera_wrap
                  %div{"data-src" => "/productos_parrilleros/1.png", "data-thumb" => "/productos_parrilleros/1t.png", "data-alignment" => "center"}
                  %div{"data-src" => "/productos_parrilleros/2.png", "data-thumb" => "/productos_parrilleros/2t.png"}
                  %div{"data-src" => "/productos_parrilleros/3.png", "data-thumb" => "/productos_parrilleros/3t.png"}
                  %div{"data-src" => "/productos_parrilleros/4.png", "data-thumb" => "/productos_parrilleros/4t.png"}
                  %div{"data-src" => "/productos_parrilleros/5.png", "data-thumb" => "/productos_parrilleros/5t.png"}
                  %div{"data-src" => "/productos_parrilleros/6.png", "data-thumb" => "/productos_parrilleros/6t.png"}
                  %div{"data-src" => "/productos_parrilleros/7.png", "data-thumb" => "/productos_parrilleros/7t.png"}
                  / #camera_wrap_3
                  / .fluid_container
:javascript
  jQuery(document).ready(function($) {

    var flag = true;
    $('#modal_parrilleros').on('show.bs.modal', function () {
      if (flag) {
        jQuery('#camera_wrap').camera({
          height: '500px',
          loader: 'bar',
          pagination: false,
          thumbnails: true,
          alignment: 'center',
          playPause: false,
          autoAdvance: false,
          fx: 'simpleFade',
          portrait: false
        });
         $(this).find('.modal-body').css({
                width:'auto',
                height:'635px',
                'max-height':'100%'
         });
         flag = false;
      }

    });
  });

app/views/main/_pantalla_1.html.haml
#pantalla_intro
  .vcenter_galeria
    .row
      .col-xs-12
        .container
          .pantalla_1#pantalla_1
            .row.vector_smart_row#vector_smart_row
              .col-xs-12.text-center
                = image_tag 'pantalla_1/vector_smart.png', alt: 'Nos une la parrilla', class: 'img-responsive vector_smart'
            .row.m_video_promocional#m_video_promocional{style: 'display:none;'}
              .col-xs-12.text-center
                %a.m_boton_video#m_boton_video{href: 'https://www.youtube.com/watch?v=mm1dIccKlAc'}
                  = image_tag 'movil/pantalla_1/ver_video_promocional.png', class: 'img-responsive m_video_img'
            .row#frase_inicial_row
              .col-xs-12.text-center
                = image_tag 'pantalla_1/frase_inicial.png', class: 'img-responsive frase_inicial'
                = image_tag 'movil/pantalla_1/texto_home.png', class: 'm_texto_home', style: 'display:none;'

            .row#boton_facebook_row
              .col-xs-12.text-center
                %button.boton_facebook#boton_facebook
                  = image_tag 'pantalla_1/facebook_connect.png', class: 'btn_facebook_connect'
                %button.boton_facebook#boton_facebook_off{style: 'display:none', disabled: 'disabled'}
                  = image_tag 'pantalla_1/facebook_connect_off.png', class: 'btn_facebook_connect'
            .row#boton_facebook_loading{style: 'display:none'}
              .col-xs-12.text-center
                %i.fa.fa-circle-o-notch.fa-2x.fa-spin
            .row#adorno_btn_fb_row
              .col-xs-12.text-center
                = image_tag 'pantalla_1/adorno_btn_fb.png'

%a#YTV.youtube{:href => "https://www.youtube.com/watch?v=mm1dIccKlAc"}

app/views/main/_row_bottom.html.haml
.row.m_row_bottom{style: 'display:none;'}
  .col-xs-3
    = link_to '/privacy.pdf' do
      = image_tag 'movil/pantalla_1/ver_bases_m.png', class: 'ver_bases_m'
  .col-xs-6
    = image_tag 'movil/pantalla_1/productos_parrilleros.png', class: 'img-responsive m_productos_parrilleros'
  .col-xs-3
    = link_to main_galeria_path do
      = image_tag 'movil/pantalla_1/ver_galeria_m.png', class: 'ver_galeria_m'

app/views/main/felicidades.html.haml
= image_tag 'pantalla_1/logo_bg.png', class: 'logo_bg img-responsive'
.vcenter_full#main_div
  .row
    .col-xs-12.col-lg-12.col-md-12
      .container
        .row.row_galeria_m{style: 'display:none'}
          .col-xs-12
            = link_to main_galeria_path do
              = image_tag 'movil/felicidades/visita_galeria_top.png', class: 'img-responsive m_visita_galeria'
        .row
          .col-xs-3
            .row.aux_relative
            .row.row_felicidades
              .col-xs-12
                = image_tag 'felicidades/texto_izquierda.png', class: 'img-responsive texto_izquierda'
                = image_tag 'felicidades/adorno_izquierdo_2.png', class: 'img-responsive img_adorno_izquierdo'
          .col-xs-6
            .row.row_galeria
              .col-xs-12
                .portrait
                  = link_to main_galeria_path do
                    = image_tag 'felicidades/visita_galeria.png', class: 'imagen_galeria'
                    = image_tag "/#{@id}/#{@img}.png", class: 'imagen_user'
          .col-xs-3
            .row.row_texto_participando
              .col-xs-12
                .row.aux_relative
                = image_tag 'felicidades/adorno_derecho_2.png', class: 'img-responsive img_adorno_derecho'
                = image_tag 'felicidades/texto_derecha.png', class: 'img-responsive texto_derecha'

.row
  .col-xs-12
    = image_tag 'felicidades/felicidades.png', class: 'navigation felicidades_img', id: 'navigation_1'
    = image_tag 'movil/felicidades/felicidades_m.png', class: 'm_felicidades', id: 'm_felicidades', style: 'display:none'
    = image_tag 'movil/felicidades/texto_m.png', class: 'texto_m', id: 'texto_m', style: 'display:none'
.row.row_bottom#row_bottom
  .col-xs-3.text-center
    = link_to 'bases' do
      = image_tag 'pantalla_2/ver_bases.png', class: 'ver_bases'
  .col-xs-6.text-center
    %button#productos_parrilleros{"data-target" => ".bs-parrilleros-modal-lg", "data-toggle" => "modal", :type => "button"}
      = image_tag 'pantalla_2/productos_parrilleros.png', class: 'img-responsive ver_productos_parrilleros'
  .col-xs-3.text-center
    = link_to main_galeria_path do
      = image_tag 'pantalla_2/ver_galeria.png', class: 'ver_bases'

= render partial: 'row_bottom'

app/views/main/index.html.haml
.fb-root#fb-root
  .row.luces_row#luces_row
    .col-xs-12
      .luces#luces

  #main_div
    = render partial: 'pantalla_1'
    //= render partial: 'main'

  .vcenter_galeria#loading_div{style: 'display:none;'}
    .row
      .col-xs-12.text-center
        %i.fa.fa-circle-o-notch.fa-5x.fa-spin

.row.row_bottom#row_bottom{style: 'display:none'}
  .col-xs-3.text-center
    = link_to '/privacy.pdf' do
      = image_tag 'pantalla_2/ver_bases.png', class: 'ver_bases'
  .col-xs-6.text-center
    %button#productos_parrilleros{"data-target" => ".bs-parrilleros-modal-lg", "data-toggle" => "modal", :type => "button"}
      = image_tag 'pantalla_2/productos_parrilleros.png', class: 'img-responsive ver_productos_parrilleros'
  .col-xs-3.text-center
    = link_to main_galeria_path do
      = image_tag 'pantalla_2/ver_galeria.png', class: 'ver_bases'

= render partial: 'row_bottom'


= render partial: 'modal_parrilleros'

app/views/main/old.html.haml
:css
  body {
      margin: 0 !important;
      padding: 0 !important;
  }
  .container {
      width: 100%;
      height: 100%;
      position: relative;
      background-color:bisque;
  }
  .btsc {
      width: 20%;
      height: 24%;
      position: absolute;
      top: 45%;
      left: 40%;
  }
.container
  = image_tag 'old/landing.png', style: "width: 100%; height: 100%;"
  %a{:href => "http://www.supercerdo.cl/"}
    .btsc

app/views/uploads/img.js.erb
alert('success!');
<% if remotipart_submitted? %>
  alert('submitted via remotipart')
<% else %>
  alert('submitted via native jquery-ujs')
<% end %>